import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type AppLanguage = 'en' | 'ur';

const STORAGE_KEY = 'dawa_language';

const en: Record<string, string> = {
  'language.english': 'English',
  'language.urdu': 'اردو',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.retry': 'Try again',
  'common.saved': 'Saved',
  'common.preview': 'Preview',
  'common.current': 'Current',
  'common.active': 'Active',
  'common.inactive': 'Inactive',
  'common.optional': 'Optional',
  'common.updateFailed': 'Could not update',
  'common.tryAgain': 'Please try again.',
  'common.patientLoadFailed': 'Could not load your patient',
  'tabs.home': 'Home',
  'tabs.medications': 'Medicines',
  'tabs.calls': 'Calls',
  'tabs.settings': 'Settings',
  'signin.tagline': 'Medication reminders in a voice patients understand.',
  'signin.title': 'Caregiver sign in',
  'signin.body': 'Manage schedules, reminder calls and patient preferences securely.',
  'signin.google': 'Continue with Google',
  'signin.privacy': 'Google is used only to identify the caregiver account.',
  'signin.backendMissing': 'Backend URL is not configured.',
  'signin.failed': 'Sign in could not be completed.',
  'onboarding.title': 'Patient setup',
  'onboarding.greeting': 'Hello, {{name}}',
  'onboarding.who': 'Who should SehatCall call?',
  'onboarding.whoBody': 'Add the patient once. These details can be changed later in Settings.',
  'onboarding.name': 'Patient name',
  'onboarding.address': 'How SehatCall should address them',
  'onboarding.addressHint': 'SehatCall uses this name during every call.',
  'onboarding.phone': 'Phone number',
  'onboarding.phoneHint': 'Include the country code. SehatCall will call once to verify the number.',
  'onboarding.callVerify': 'Call to verify',
  'onboarding.checkPhone': 'Verify the phone',
  'onboarding.codeBody': 'SehatCall is calling {{phone}} and will read a six digit code.',
  'onboarding.code': 'Verification code',
  'onboarding.confirm': 'Confirm code',
  'onboarding.resend': 'Call again',
  'onboarding.resendIn': 'Call again in {{seconds}} seconds',
  'onboarding.changeNumber': 'Change number',
  'onboarding.signOut': 'Sign out',
  'onboarding.nameExample': 'Example: Razia Bibi',
  'onboarding.addressExample': 'Example: Ammi',
  'onboarding.backendMissing': 'Backend URL is not configured. Add it in Settings and try again.',
  'onboarding.completeFields': 'Complete all three fields.',
  'onboarding.callingAgain': 'Calling again now.',
  'onboarding.enterCode': 'Enter the code you heard on the call.',
  'onboarding.failed': 'The request could not be completed. Please try again.',
  'home.subtitle': 'Reminder care for {{name}}',
  'home.next': 'Next call',
  'home.dueNow': 'Due now',
  'home.remaining': 'remaining',
  'home.scheduledAt': 'Scheduled at {{time}}',
  'home.autoOff': 'Automatic calls are off for this medicine.',
  'home.callNow': 'Call now',
  'home.calling': 'Calling {{name}}',
  'home.noUpcoming': 'No upcoming call',
  'home.noUpcomingBody': 'Add an active medicine with automatic calls enabled.',
  'home.recent': 'Recent call',
  'home.outcome': 'Outcome',
  'home.schedule': 'Medicine schedule',
  'home.noActive': 'No active medicines',
  'home.hours': '{{value}} hr',
  'home.minutes': '{{value}} min',
  'home.seconds': '{{value}} sec',
  'calls.title': 'Call history',
  'calls.count': '{{count}} calls',
  'calls.medication': 'Medicine',
  'calls.adherence': 'Adherence',
  'calls.empty': 'No calls yet',
  'calls.emptyBody': 'Reminder calls will appear here. Call completion and medicine adherence remain separate.',
  'calls.loadError': 'Could not load calls',
  'adherence.taken': 'Taken',
  'adherence.notTaken': 'Not taken',
  'adherence.unknown': 'Outcome not confirmed',
  'status.completed': 'Completed',
  'status.answered': 'Answered',
  'status.failed': 'Not connected',
  'status.calling': 'Calling',
  'status.dispatched': 'Dispatched',
  'status.ringing': 'Ringing',
  'status.scheduled': 'Scheduled',
  'meds.title': 'Medicines',
  'meds.add': 'Add medicine',
  'meds.empty': 'No medicines yet',
  'meds.emptyBody': 'Add the patient medicine schedule to begin reminder calls.',
  'meds.addFirst': 'Add first medicine',
  'meds.automaticCalls': 'Automatic calls',
  'meds.doctor': 'Doctor',
  'meds.package': 'Package',
  'meds.stripe': 'Stripe',
  'meds.shape': 'Shape',
  'meds.stored': 'Stored',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.account': 'Account',
  'settings.caregiver': 'Caregiver',
  'settings.signOut': 'Sign out',
  'settings.patient': 'Patient',
  'settings.name': 'Name',
  'settings.address': 'How SehatCall addresses the patient',
  'settings.savePatient': 'Save patient details',
  'settings.voice': 'SehatCall voice',
  'settings.voiceBody': 'Choose the voice {{name}} hears on reminder calls.',
  'settings.updatingVoice': 'Updating voice',
  'settings.connection': 'Connection',
  'settings.backendUrl': 'Backend URL',
  'settings.reconnect': 'Save and reconnect',
  'settings.developer': 'Developer tools',
  'settings.voiceFailed': 'Voice not changed',
  'settings.previewFailed': 'Preview could not be played.',
  'settings.notConnected': 'Not connected',
  'settings.configureBackend': 'Configure the backend URL first.',
  'form.addTitle': 'Add medicine',
  'form.editTitle': 'Edit medicine',
  'form.medication': 'Medicine',
  'form.clinicalName': 'Clinical name',
  'form.nickname': 'Patient nickname',
  'form.nicknameHint': 'The name the patient uses for this medicine.',
  'form.dosage': 'Dosage',
  'form.doseInstruction': 'Dose instruction',
  'form.foodInstruction': 'Food instruction',
  'form.schedule': 'Schedule',
  'form.callTime': 'Call time',
  'form.timeHint': 'Use 24 hour time as HH:MM.',
  'form.routineAnchor': 'Routine anchor',
  'form.routineHint': 'A familiar event that helps the patient remember.',
  'form.automaticCalls': 'Automatic calls',
  'form.automaticCallsHint': 'SehatCall calls at the scheduled time.',
  'form.identification': 'Medicine identification',
  'form.identificationBody': 'Add visible details that help the patient identify the correct medicine without reading.',
  'form.packageColour': 'Package colour',
  'form.stripeColour': 'Stripe colour',
  'form.tabletShape': 'Tablet shape',
  'form.storage': 'Storage location',
  'form.doctorInstructions': 'Doctor instructions',
  'form.doctorBody': 'SehatCall never overrides the structured medicine details above.',
  'form.doctorName': 'Doctor name',
  'form.instructions': 'Instructions',
  'form.callPatient': 'Call patient now',
  'form.savedReview': 'Saved. Please review',
  'form.return': 'Return to medicines',
  'form.requiredClinical': 'Clinical name is required.',
  'form.requiredDosage': 'Dosage is required.',
  'form.requiredDose': 'Dose instruction is required.',
  'form.invalidTime': 'Enter the call time as HH:MM using 24 hour time.',
  'form.saveFailed': 'Medicine could not be saved.',
  'form.caution': 'Caution',
  'form.calling': 'Calling patient',
  'form.callDispatched': 'Call requested',
  'form.callDispatchedBody': 'SehatCall is calling {{name}} now.',
  'form.callFailed': 'Call could not be requested.',
  'form.exampleClinical': 'Example: Metformin',
  'form.exampleNickname': 'Example: night tablet',
  'form.exampleDosage': 'Example: 500 mg',
  'form.exampleDose': 'Example: 1 tablet',
  'form.exampleFood': 'Example: after dinner',
  'form.exampleRoutine': 'Example: after dinner',
  'form.exampleColour': 'Example: white',
  'form.exampleDoctor': 'Example: Dr Ahmed',
  'form.exampleInstructions': 'Example: Take with a full glass of water',
  'notFound.title': 'Screen not found',
  'notFound.home': 'Return home',
  'error.title': 'Something went wrong',
  'error.body': 'Restart the app to continue.',
  'error.details': 'Error details',
  'dev.title': 'Developer tools',
  'dev.warning': 'Testing actions can place calls and change demo data.',
  'dev.medicine': 'Medicine',
  'dev.manualCall': 'Manual call',
  'dev.callNow': 'Call now',
  'dev.schedule': 'Schedule demo call',
  'dev.delay': 'Delay in seconds from 15 to 300',
  'dev.scheduleAction': 'Schedule call',
  'dev.reset': 'Reset demo data',
  'dev.resetBody': 'This clears call records and keeps medicine data.',
  'dev.backend': 'Backend status',
  'dev.apiUrl': 'API URL',
  'dev.patient': 'Patient',
  'dev.medicines': 'Medicines',
  'dev.callPhase': 'Call phase',
  'dev.recentCalls': 'Recent calls',
  'dev.notSet': 'Not set',
  'dev.notLoaded': 'Not loaded',
  'dev.noMedicine': 'Select a medicine first.',
  'dev.invalidDelay': 'Enter a delay from 15 to 300 seconds.',
  'dev.dispatched': 'Call requested',
  'dev.failed': 'Action failed',
  'dev.scheduled': 'Scheduled',
  'dev.remaining': '{{seconds}} seconds remaining',
};

const ur: Record<string, string> = {
  'language.english': 'English',
  'language.urdu': 'اردو',
  'common.save': 'محفوظ کریں',
  'common.cancel': 'منسوخ کریں',
  'common.back': 'واپس',
  'common.retry': 'دوبارہ کوشش کریں',
  'common.saved': 'محفوظ ہوگیا',
  'common.preview': 'آواز سنیں',
  'common.current': 'موجودہ',
  'common.active': 'فعال',
  'common.inactive': 'غیر فعال',
  'common.optional': 'اختیاری',
  'common.updateFailed': 'تبدیلی محفوظ نہیں ہو سکی',
  'common.tryAgain': 'دوبارہ کوشش کریں۔',
  'common.patientLoadFailed': 'مریض کی معلومات لوڈ نہیں ہو سکیں',
  'tabs.home': 'گھر',
  'tabs.medications': 'ادویات',
  'tabs.calls': 'کالز',
  'tabs.settings': 'ترتیبات',
  'signin.tagline': 'مریض کی سمجھ میں آنے والی آواز میں دوا کی یاد دہانی۔',
  'signin.title': 'کیئرگیور سائن ان',
  'signin.body': 'ادویات کے اوقات، یاد دہانی کالز اور مریض کی ترجیحات محفوظ طریقے سے سنبھالیں۔',
  'signin.google': 'گوگل کے ساتھ جاری رکھیں',
  'signin.privacy': 'گوگل صرف کیئرگیور اکاؤنٹ کی شناخت کے لیے استعمال ہوتا ہے۔',
  'signin.backendMissing': 'بیک اینڈ یو آر ایل موجود نہیں ہے۔',
  'signin.failed': 'سائن ان مکمل نہیں ہو سکا۔',
  'onboarding.title': 'مریض کی ترتیب',
  'onboarding.greeting': 'السلام علیکم، {{name}}',
  'onboarding.who': 'SehatCall کس کو کال کرے؟',
  'onboarding.whoBody': 'مریض کی معلومات صرف ایک بار شامل کریں۔ بعد میں ترتیبات سے تبدیل کی جا سکتی ہیں۔',
  'onboarding.name': 'مریض کا نام',
  'onboarding.address': 'SehatCall مریض کو کس نام سے پکارے',
  'onboarding.addressHint': 'SehatCall ہر کال میں یہی نام استعمال کرے گا۔',
  'onboarding.phone': 'فون نمبر',
  'onboarding.phoneHint': 'ملکی کوڈ شامل کریں۔ نمبر کی تصدیق کے لیے SehatCall ایک کال کرے گا۔',
  'onboarding.callVerify': 'تصدیقی کال کریں',
  'onboarding.checkPhone': 'فون کی تصدیق',
  'onboarding.codeBody': 'SehatCall {{phone}} پر کال کر کے چھ ہندسوں کا کوڈ سنائے گا۔',
  'onboarding.code': 'تصدیقی کوڈ',
  'onboarding.confirm': 'کوڈ کی تصدیق کریں',
  'onboarding.resend': 'دوبارہ کال کریں',
  'onboarding.resendIn': '{{seconds}} سیکنڈ بعد دوبارہ کال کریں',
  'onboarding.changeNumber': 'نمبر تبدیل کریں',
  'onboarding.signOut': 'سائن آؤٹ',
  'onboarding.nameExample': 'مثال: رضیہ بی بی',
  'onboarding.addressExample': 'مثال: امی',
  'onboarding.backendMissing': 'بیک اینڈ یو آر ایل موجود نہیں ہے۔ ترتیبات میں شامل کر کے دوبارہ کوشش کریں۔',
  'onboarding.completeFields': 'تینوں خانے مکمل کریں۔',
  'onboarding.callingAgain': 'دوبارہ کال ہو رہی ہے۔',
  'onboarding.enterCode': 'کال میں سنا ہوا کوڈ درج کریں۔',
  'onboarding.failed': 'درخواست مکمل نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
  'home.subtitle': '{{name}} کی دوا کی یاد دہانی',
  'home.next': 'اگلی کال',
  'home.dueNow': 'ابھی وقت ہے',
  'home.remaining': 'باقی',
  'home.scheduledAt': 'وقت {{time}}',
  'home.autoOff': 'اس دوا کے لیے خودکار کالز بند ہیں۔',
  'home.callNow': 'ابھی کال کریں',
  'home.calling': '{{name}} کو کال ہو رہی ہے',
  'home.noUpcoming': 'کوئی آنے والی کال نہیں',
  'home.noUpcomingBody': 'خودکار کال کے ساتھ ایک فعال دوا شامل کریں۔',
  'home.recent': 'حالیہ کال',
  'home.outcome': 'نتیجہ',
  'home.schedule': 'ادویات کا شیڈول',
  'home.noActive': 'کوئی فعال دوا نہیں',
  'home.hours': '{{value}} گھنٹے',
  'home.minutes': '{{value}} منٹ',
  'home.seconds': '{{value}} سیکنڈ',
  'calls.title': 'کال کی تفصیل',
  'calls.count': '{{count}} کالز',
  'calls.medication': 'دوا',
  'calls.adherence': 'دوا لینے کی تصدیق',
  'calls.empty': 'ابھی کوئی کال نہیں',
  'calls.emptyBody': 'یاد دہانی کالز یہاں نظر آئیں گی۔ کال مکمل ہونا دوا لینے کی تصدیق نہیں ہے۔',
  'calls.loadError': 'کالز لوڈ نہیں ہو سکیں',
  'adherence.taken': 'دوا لے لی',
  'adherence.notTaken': 'دوا نہیں لی',
  'adherence.unknown': 'نتیجے کی تصدیق نہیں ہوئی',
  'status.completed': 'مکمل',
  'status.answered': 'جواب دیا',
  'status.failed': 'رابطہ نہیں ہوا',
  'status.calling': 'کال جاری',
  'status.dispatched': 'کال بھیج دی گئی',
  'status.ringing': 'گھنٹی ہو رہی ہے',
  'status.scheduled': 'طے شدہ',
  'meds.title': 'ادویات',
  'meds.add': 'دوا شامل کریں',
  'meds.empty': 'ابھی کوئی دوا نہیں',
  'meds.emptyBody': 'یاد دہانی کالز شروع کرنے کے لیے مریض کی ادویات شامل کریں۔',
  'meds.addFirst': 'پہلی دوا شامل کریں',
  'meds.automaticCalls': 'خودکار کالز',
  'meds.doctor': 'ڈاکٹر',
  'meds.package': 'پیکٹ',
  'meds.stripe': 'دھاری',
  'meds.shape': 'شکل',
  'meds.stored': 'جگہ',
  'settings.title': 'ترتیبات',
  'settings.language': 'زبان',
  'settings.account': 'اکاؤنٹ',
  'settings.caregiver': 'کیئرگیور',
  'settings.signOut': 'سائن آؤٹ',
  'settings.patient': 'مریض',
  'settings.name': 'نام',
  'settings.address': 'SehatCall مریض کو کس نام سے پکارے',
  'settings.savePatient': 'مریض کی معلومات محفوظ کریں',
  'settings.voice': 'SehatCall کی آواز',
  'settings.voiceBody': 'یاد دہانی کالز کے لیے {{name}} کی پسندیدہ آواز منتخب کریں۔',
  'settings.updatingVoice': 'آواز تبدیل ہو رہی ہے',
  'settings.connection': 'کنکشن',
  'settings.backendUrl': 'بیک اینڈ یو آر ایل',
  'settings.reconnect': 'محفوظ کر کے دوبارہ جڑیں',
  'settings.developer': 'ڈیولپر ٹولز',
  'settings.voiceFailed': 'آواز تبدیل نہیں ہوئی',
  'settings.previewFailed': 'آواز نہیں چل سکی۔',
  'settings.notConnected': 'کنکشن موجود نہیں',
  'settings.configureBackend': 'پہلے بیک اینڈ یو آر ایل درج کریں۔',
  'form.addTitle': 'دوا شامل کریں',
  'form.editTitle': 'دوا میں تبدیلی',
  'form.medication': 'دوا',
  'form.clinicalName': 'طبی نام',
  'form.nickname': 'مریض کا رکھا ہوا نام',
  'form.nicknameHint': 'مریض اس دوا کو جس نام سے جانتا ہے۔',
  'form.dosage': 'مقدار',
  'form.doseInstruction': 'خوراک کی ہدایت',
  'form.foodInstruction': 'کھانے سے متعلق ہدایت',
  'form.schedule': 'وقت',
  'form.callTime': 'کال کا وقت',
  'form.timeHint': 'چوبیس گھنٹے کے وقت میں HH:MM لکھیں۔',
  'form.routineAnchor': 'روزمرہ کا حوالہ',
  'form.routineHint': 'ایسا معمول جو مریض کو وقت یاد رکھنے میں مدد دے۔',
  'form.automaticCalls': 'خودکار کالز',
  'form.automaticCallsHint': 'SehatCall مقررہ وقت پر کال کرے گا۔',
  'form.identification': 'دوا کی پہچان',
  'form.identificationBody': 'ایسی ظاہری نشانیاں شامل کریں جن سے مریض بغیر پڑھے صحیح دوا پہچان سکے۔',
  'form.packageColour': 'پیکٹ کا رنگ',
  'form.stripeColour': 'دھاری کا رنگ',
  'form.tabletShape': 'گولی کی شکل',
  'form.storage': 'رکھنے کی جگہ',
  'form.doctorInstructions': 'ڈاکٹر کی ہدایات',
  'form.doctorBody': 'SehatCall اوپر دی گئی تصدیق شدہ معلومات کو تبدیل نہیں کرتا۔',
  'form.doctorName': 'ڈاکٹر کا نام',
  'form.instructions': 'ہدایات',
  'form.callPatient': 'مریض کو ابھی کال کریں',
  'form.savedReview': 'محفوظ ہوگیا۔ براہ کرم جائزہ لیں',
  'form.return': 'ادویات پر واپس جائیں',
  'form.requiredClinical': 'دوا کا طبی نام ضروری ہے۔',
  'form.requiredDosage': 'دوا کی مقدار ضروری ہے۔',
  'form.requiredDose': 'خوراک کی ہدایت ضروری ہے۔',
  'form.invalidTime': 'کال کا وقت چوبیس گھنٹے کے حساب سے HH:MM میں لکھیں۔',
  'form.saveFailed': 'دوا محفوظ نہیں ہو سکی۔',
  'form.caution': 'احتیاط',
  'form.calling': 'مریض کو کال ہو رہی ہے',
  'form.callDispatched': 'کال کی درخواست بھیج دی گئی',
  'form.callDispatchedBody': 'SehatCall اب {{name}} کو کال کر رہا ہے۔',
  'form.callFailed': 'کال کی درخواست نہیں بھیجی جا سکی۔',
  'form.exampleClinical': 'مثال: میٹفارمن',
  'form.exampleNickname': 'مثال: رات والی گولی',
  'form.exampleDosage': 'مثال: 500 ملی گرام',
  'form.exampleDose': 'مثال: ایک گولی',
  'form.exampleFood': 'مثال: رات کے کھانے کے بعد',
  'form.exampleRoutine': 'مثال: رات کے کھانے کے بعد',
  'form.exampleColour': 'مثال: سفید',
  'form.exampleDoctor': 'مثال: ڈاکٹر احمد',
  'form.exampleInstructions': 'مثال: ایک گلاس پانی کے ساتھ لیں',
  'notFound.title': 'صفحہ نہیں ملا',
  'notFound.home': 'گھر واپس جائیں',
  'error.title': 'کچھ درست نہیں ہوا',
  'error.body': 'جاری رکھنے کے لیے ایپ دوبارہ شروع کریں۔',
  'error.details': 'خرابی کی تفصیل',
  'dev.title': 'ڈیولپر ٹولز',
  'dev.warning': 'ٹیسٹ کے اقدامات کال کر سکتے ہیں اور ڈیمو ڈیٹا تبدیل کر سکتے ہیں۔',
  'dev.medicine': 'دوا',
  'dev.manualCall': 'دستی کال',
  'dev.callNow': 'ابھی کال کریں',
  'dev.schedule': 'ڈیمو کال کا وقت',
  'dev.delay': 'پندرہ سے تین سو سیکنڈ کی تاخیر',
  'dev.scheduleAction': 'کال طے کریں',
  'dev.reset': 'ڈیمو ڈیٹا صاف کریں',
  'dev.resetBody': 'اس سے کال ریکارڈ صاف ہوں گے اور ادویات محفوظ رہیں گی۔',
  'dev.backend': 'بیک اینڈ کی حالت',
  'dev.apiUrl': 'اے پی آئی یو آر ایل',
  'dev.patient': 'مریض',
  'dev.medicines': 'ادویات',
  'dev.callPhase': 'کال کی حالت',
  'dev.recentCalls': 'حالیہ کالز',
  'dev.notSet': 'موجود نہیں',
  'dev.notLoaded': 'لوڈ نہیں ہوا',
  'dev.noMedicine': 'پہلے ایک دوا منتخب کریں۔',
  'dev.invalidDelay': 'پندرہ سے تین سو سیکنڈ کی تاخیر درج کریں۔',
  'dev.dispatched': 'کال کی درخواست بھیج دی گئی',
  'dev.failed': 'کارروائی مکمل نہیں ہوئی',
  'dev.scheduled': 'طے شدہ',
  'dev.remaining': '{{seconds}} سیکنڈ باقی',
};

interface LanguageValue {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  isUrdu: boolean;
  t: (key: string, values?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('en');

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((saved) => {
      if (saved === 'en' || saved === 'ur') setLanguageState(saved);
    });
  }, []);

  const setLanguage = useCallback(async (next: AppLanguage) => {
    setLanguageState(next);
    await AsyncStorage.setItem(STORAGE_KEY, next);
  }, []);

  const t = useCallback((key: string, values?: Record<string, string | number>) => {
    const source = language === 'ur' ? ur : en;
    let result = source[key] ?? en[key] ?? key;
    for (const [name, value] of Object.entries(values ?? {})) {
      result = result.replaceAll(`{{${name}}}`, String(value));
    }
    return result;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    isUrdu: language === 'ur',
    t,
  }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageValue {
  const value = useContext(LanguageContext);
  if (!value) throw new Error('useLanguage must be used inside LanguageProvider');
  return value;
}
